### ISSUE TITLE
Enhancements : Selected Section Should be more visible || UI Improvements for Sections and Buttons.

### ISSUE THREAD

**Issue by Shariq2003** [BishalDe/TaskMate#25]
![image](https://github.com/bishalde/TaskMate/assets/109452033/e7a9052b-7800-435f-8d7a-4a31b2a3692d)

@bishalde sir, Assign this task to me.

**Comment by GnanariddhikaRavikumar** [comment]
I can work on the improvement of this UI Design , can you assign me this task
