### ISSUE TITLE
Issue: Unwanted To-Do Tasks Added Without Titles

### ISSUE THREAD

**Issue by Aniket-2504** [BishalDe/TaskMate#40]
**Dear @bishalde ,**

### I identified an issue with your to-do list web app that requires attention:

**When adding a to-do task to a list, the app only prompts for date and time, omitting the requirement for a title. This leads to tasks being added without titles, creating unwanted entries in the list.**

I'm interested in addressing this issue and providing my best effort to resolve it. Ensuring that users are prompted to add a title along with date and time will improve the organization and usability of the to-do list.

I have recorded a video demonstrating this issue for clarity: 

https://github.com/bishalde/TaskMate/assets/145179532/f5f1557d-6791-40ef-bf54-fc1ddc0546da

Please consider assigning me this task, and I will work diligently to fix this bug and enhance the functionality of your web app.

I look forward to hearing from you soon.

**Comment by Kalyan9064** [comment]
I would like to work on this . Please could you assign me this issue under GSSOC'24
