### ISSUE TITLE
[Feature] Add Dark mode to the website

### ISSUE THREAD

**Issue by TusharKumarChopra** [bishalde/TaskMate#7]
I would like to add a dark mode to the website. Please assign this to me.

**Comment by bishalde** [comment]
Thanyou @TusharKumarChopra for finding this issue.
Sure, you can proceed with it.!


```bash
git fetch origin
git checkout darkmode
```
I have created a new branch, push the changes in that branch!

And feel free to give this Repository a STAR⭐ and follow back 😊.

**Comment by Pratyaksh0910** [comment]
Hey there! I'm Pratyaksh Agrawal, a full-stack MERN web developer. With experience in numerous successful MERN stack projects, I excel in HTML, CSS,JavaScript,C, C++,jQuery, Node.js, React.js, Bootstrap, Tailwind, Express, MongoDB, API,GraphQL,WebRTC.
You can find me on LinkedIn : https://www.linkedin.com/in/pratyaksh-agrawal-2aa032220/
Looking forward to contributing to GSSOC 2024!

**Comment by bishalde** [comment]
#14 DOne

**Comment by TusharKumarChopra** [comment]
@bishalde Please assign Level for gssoc.
